# Generated by Django 6.0.3 on 2026-03-18 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recinto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=100)),
                ('asiento_electoral', models.CharField(max_length=100)),
                ('distrito', models.CharField(max_length=100)),
                ('zona', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=255)),
                ('nro_mesas', models.IntegerField(default=0)),
                ('codigo', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True)),
                ('ruta', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Transmision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('hora', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coordinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('celular', models.CharField(db_index=True, max_length=20, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('celular', models.CharField(db_index=True, max_length=20, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Acta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('recinto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.recinto')),
            ],
        ),
        migrations.CreateModel(
            name='Soporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('celular', models.CharField(db_index=True, max_length=20, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido_materno', models.CharField(blank=True, max_length=100, null=True)),
                ('celular', models.CharField(max_length=100)),
                ('ci', models.CharField(db_index=True, max_length=50, unique=True)),
                ('coordinador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='control.coordinador')),
                ('monitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='control.monitor')),
                ('recinto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='control.recinto')),
                ('soporte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='control.soporte')),
            ],
        ),
        migrations.CreateModel(
            name='ReporteTransmision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('TRANSMITIDO', 'Transmitido'), ('REVISADO_RECHAZADO', 'Revisado rechazado'), ('SIN_ENVIAR', 'Sin enviar'), ('ENVIADO_NO_REVISADO', 'Enviado no revisado')], default='SIN_ENVIAR', max_length=20)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('acta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.acta')),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='control.operador')),
                ('transmision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.transmision')),
            ],
            options={
                'indexes': [models.Index(fields=['transmision'], name='control_rep_transmi_c09c6e_idx'), models.Index(fields=['estado'], name='control_rep_estado_2fe465_idx'), models.Index(fields=['operador'], name='control_rep_operado_89dc91_idx')],
            },
        ),
    ]
