# Generated by Django 6.0.3 on 2026-03-18 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinador',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='coordinador',
            name='apellido_paterno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='coordinador',
            name='ci',
            field=models.CharField(db_index=True, default=123, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monitor',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='monitor',
            name='apellido_paterno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='monitor',
            name='ci',
            field=models.CharField(db_index=True, default=123, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soporte',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='soporte',
            name='apellido_paterno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='soporte',
            name='ci',
            field=models.CharField(db_index=True, default=123, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coordinador',
            name='celular',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='celular',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='soporte',
            name='celular',
            field=models.CharField(max_length=20),
        ),
    ]
