# Generated by Django 6.0.3 on 2026-03-19 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_coordinador_apellido_materno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='reportetransmision',
            unique_together={('acta', 'transmision')},
        ),
        migrations.CreateModel(
            name='ReporteActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realizado', models.BooleanField(default=False)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.actividad')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.operador')),
            ],
        ),
    ]
