# Generated by Django 6.0.3 on 2026-03-19 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_actividad_alter_reportetransmision_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acta',
            name='operador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='control.operador'),
        ),
    ]
