# Generated by Django 6.0.3 on 2026-03-19 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_acta_operador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acta',
            name='recinto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='control.recinto'),
        ),
        migrations.AlterField(
            model_name='reporteactividad',
            name='operador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='control.operador'),
        ),
    ]
